# Site settings
title: Jekyll Theme Waves
description: >- # this means to ignore newlines until "baseurl:"
  A Jekyll site template designed by <a href="moodule@protonmail.com">DM</a> for <a href="https://github.com/moodule">MOODULE</a>.<br />
  It’s responsive, built on HTML5/CSS3, and entirely free<br /> under the <a href="https://github.com/moodule/jekyll-theme-consulting/blob/master/LICENSE">Creative Commons license</a>.

# Contact information
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555
email: youremailaddress@gmail.com

# Build settings
permalink: pretty
markdown: kramdown
sass:
  style: compressed
plugins:
  - jekyll-seo-tag

# Publication settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://moodule.github.io/jekyll-theme-waves" # the base hostname & protocol for your site, e.g. http://example.com
author: Moodule
copyright:
  holder: Untitled
  license: CC0 BY-NC-SA

# Exclude from processing
